dbt_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /results/dbt.duckdb
      threads: 4
      extensions:
        - httpfs
      filesystems:
        - fs: s3
          anon: false
          key: adminuser
          secret: admin123
          client_kwargs:
            endpoint_url: "http://minio:9000"
      external_root: "s3://datalake"

